# Generated by Django 5.2.2 on 2025-06-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tipo_usuario',
            new_name='type_user',
        ),
    ]
