# Generated by Django 5.2.2 on 2025-06-09 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_rename_tipo_usuario_user_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve estar no formato: (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números e espaços, mas não pode começar ou terminar com espaço.', regex='^[A-Za-z0-9À-ÿ]+(?: [A-Za-z0-9À-ÿ]+)*$')]),
        ),
    ]
