# Generated by Django 5.2.2 on 2025-06-09 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='O endereço MAC deve estar no formato: XX:XX:XX:XX:XX:XX', regex='^([0-9A-Fa-f]{2}[:]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Digite o email corretamente, deve conter letras minúsculas, números e ponto antes do @, seguido por um domínio.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
    ]
