# Generated by Django 5.2.2 on 2025-06-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alter_sensor_mac_address_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
