# Generated by Django 5.2.2 on 2025-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_alter_sensor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type_sensors',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('contador', 'Contador_pessoas'), ('luminosidade', 'Luminosidade')], max_length=50),
        ),
    ]
