# Generated by Django 5.2.2 on 2025-06-19 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_alter_sensor_type_sensors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números e espaços, mas não pode começar ou terminar com espaço.', regex='^[A-Za-z0-9À-ÿ]+(?: [A-Za-z0-9À-ÿ]+)*$')]),
        ),
    ]
