# Generated by Django 5.2.2 on 2025-06-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
